// <auto-generated />
using System;
using LoanApplication.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanApplication.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20261009145604_u")]
    partial class u
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanApp.Models.CibilReport", b =>
                {
                    b.Property<int>("CibilReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CibilReportId"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CibilScore")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CibilReportId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CibilReports");
                });

            modelBuilder.Entity("LoanApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AadhaarNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyInvestement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LoanApp.Models.DealReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewId");

                    b.HasIndex("DealId");

                    b.HasIndex("OfficerId");

                    b.ToTable("DealReviews");
                });

            modelBuilder.Entity("LoanApp.Models.Disbursement", b =>
                {
                    b.Property<int>("DisbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisbursementId"));

                    b.Property<string>("BankPartner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<decimal>("DisburseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisbursementId");

                    b.HasIndex("DealId");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("LoanApp.Models.EligibilityResult", b =>
                {
                    b.Property<int>("EligibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EligibilityId"));

                    b.Property<int>("CibilScore")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("IsEligible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EligibilityId");

                    b.HasIndex("CustomerId");

                    b.ToTable("EligibilityResults");
                });

            modelBuilder.Entity("LoanApp.Models.EmiSchedule", b =>
                {
                    b.Property<int>("EmiScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmiScheduleId"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Emi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmiScheduleId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("EmiSchedules");
                });

            modelBuilder.Entity("LoanApp.Models.ForeClosureRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ForeClosureAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ForeClosureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PartialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("ForeClosureRequests");
                });

            modelBuilder.Entity("LoanApp.Models.InterestAccrual", b =>
                {
                    b.Property<int>("AccrualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccrualId"));

                    b.Property<DateTime>("AccrualDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccrualId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("InterestAccruals");
                });

            modelBuilder.Entity("LoanApp.Models.KycDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("KycDocuments");
                });

            modelBuilder.Entity("LoanApp.Models.LoanAccount", b =>
                {
                    b.Property<int>("LoanAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanAccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanAccountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealId");

                    b.ToTable("LoanAccounts");
                });

            modelBuilder.Entity("LoanApp.Models.LoanClosure", b =>
                {
                    b.Property<int>("ClosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClosureId"));

                    b.Property<int>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosureStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalSettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClosureId");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("LoanClosures");
                });

            modelBuilder.Entity("LoanApp.Models.LoanDeal", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmiDay")
                        .HasColumnType("int");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("DealId");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanDeals");
                });

            modelBuilder.Entity("LoanApp.Models.LoanPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PenaltyPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("LoanApp.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LoanApp.Models.PenaltyCharge", b =>
                {
                    b.Property<int>("PenaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenaltyId"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelayDays")
                        .HasColumnType("int");

                    b.Property<int>("EmiScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PenaltyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PenaltyId");

                    b.HasIndex("EmiScheduleId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("PenaltyCharges");
                });

            modelBuilder.Entity("LoanApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LoanApp.Models.SanctionLetter", b =>
                {
                    b.Property<int>("SanctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanctionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("SanctionId");

                    b.HasIndex("DealId");

                    b.ToTable("SanctionLetters");
                });

            modelBuilder.Entity("LoanApp.Models.ScoreCard", b =>
                {
                    b.Property<int>("ScoreCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreCardId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("EligibleLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScoreCardId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ScoreCards");
                });

            modelBuilder.Entity("LoanApp.Models.SupportTicket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanAccountId")
                        .HasColumnType("int");

                    b.Property<string>("OfficerResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanAccountId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("LoanApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoanApp.Models.CibilReport", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany("CibilReports")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanApp.Models.DealReview", b =>
                {
                    b.HasOne("LoanApp.Models.LoanDeal", "LoanDeal")
                        .WithMany("DealReviews")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanApp.Models.User", "User")
                        .WithMany("DealReviews")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanDeal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanApp.Models.Disbursement", b =>
                {
                    b.HasOne("LoanApp.Models.LoanDeal", "LoanDeal")
                        .WithMany("Disbursements")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanDeal");
                });

            modelBuilder.Entity("LoanApp.Models.EligibilityResult", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany("EligibilityResults")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanApp.Models.EmiSchedule", b =>
                {
                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.ForeClosureRequest", b =>
                {
                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.InterestAccrual", b =>
                {
                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.KycDocument", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany("KycDocuments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanApp.Models.LoanAccount", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanApp.Models.LoanDeal", "LoanDeal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanDeal");
                });

            modelBuilder.Entity("LoanApp.Models.LoanClosure", b =>
                {
                    b.HasOne("LoanApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanApp.Models.LoanDeal", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany("LoanDeals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanApp.Models.LoanPayment", b =>
                {
                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.PenaltyCharge", b =>
                {
                    b.HasOne("LoanApp.Models.EmiSchedule", "EmiSchedule")
                        .WithMany()
                        .HasForeignKey("EmiScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EmiSchedule");

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.SanctionLetter", b =>
                {
                    b.HasOne("LoanApp.Models.LoanDeal", "LoanDeal")
                        .WithMany("SanctionLetters")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoanDeal");
                });

            modelBuilder.Entity("LoanApp.Models.ScoreCard", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany("ScoreCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanApp.Models.SupportTicket", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanApp.Models.LoanAccount", "LoanAccount")
                        .WithMany()
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("LoanApp.Models.User", b =>
                {
                    b.HasOne("LoanApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LoanApp.Models.Customer", b =>
                {
                    b.Navigation("CibilReports");

                    b.Navigation("EligibilityResults");

                    b.Navigation("KycDocuments");

                    b.Navigation("LoanDeals");

                    b.Navigation("ScoreCards");
                });

            modelBuilder.Entity("LoanApp.Models.LoanDeal", b =>
                {
                    b.Navigation("DealReviews");

                    b.Navigation("Disbursements");

                    b.Navigation("SanctionLetters");
                });

            modelBuilder.Entity("LoanApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LoanApp.Models.User", b =>
                {
                    b.Navigation("DealReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
